version: '3'

services:
###> doctrine/doctrine-bundle ###
  mysql:
      image: mysql:8.0
      restart: "no"
      command: "--default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0"
      ports:
        - 3346:3306
      healthcheck:
        test: "/etc/init.d/mysql status"
        timeout: 1s
        retries: 60
      volumes:
        - "./docker/db/mysql:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: p@ssword
        MYSQL_DATABASE: comptabook
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
